title: OpenRiak QuickDocs
description: Documentation for the OpenRiak Riak project
theme: just-the-docs

plugins:
  - jekyll-relative-links

url: https://martinsumner.github.io/riak_kv/

aux_links:
  "Discuss OpenRiak on GitHub": https://github.com/orgs/OpenRiak/discussions

logo: "/assets/images/openriak_cropped.png"

favicon_ico: "/assets/images/favicon.ico"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"