title: OpenRiak Quick Docs
description: starter documentation for the OpenRiak Riak project
theme: just-the-docs

plugins:
  - jekyll-relative-links

url: https://martinsumner.github.io/riak_kv/

aux_links:
  OpenRiak: https://github.com/OpenRiak

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    color: purple
  warning:
    title: Warning
    color: red